/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package example3.app;

public class App {
    public static void main(String[] args) {
        int number = 10;
        double result;

        result = number + 6; //Addition
        System.out.println(number+"+6="+result);

        result = number - 8; //Subtraction
        System.out.println(number+"-8="+result);

        result = number * 4; //Multiplication
        System.out.println(number+"*4="+result);

        result = number / 5; //Division
        System.out.println(number+"/5="+result);

        result = number % 3; //Rest of the division, module
        System.out.println(number+"%3="+result);
    }
}
