package app;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.BufferedReader;

/*
 * This Java source file was generated by the Gradle 'init' task.
 
/*class name must have file name. Java functions must be putted under a class. for each function we have to specify if it's public or private
  static because members that need to access other class members require static type, like C++ (tho that's limited from class to class, not in 
  the same class).*/
public class App {

    String scanfString (String msg) throws IOException {
        String strInput;
        
        InputStreamReader in = new InputStreamReader(System.in);
        BufferedReader inputTastiera = new BufferedReader(in);
        strInput = inputTastiera.readLine();
        System.out.println(msg);
        return strInput;
    }

public static void main(String[] args) {
     string strinput;
     App object = new App();
     try {
        object.scanfString(strinput);
     } catch (Exception e) {
        
     }
    }
}


   
